source 'https://rubygems.org'

gem 'rails', '4.1.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
# group :assets do
gem 'sass-rails'
gem 'coffee-rails'
#
#   # See https://github.com/sstephenson/execjs#readme for more supported runtimes
#
gem 'uglifier'
# end


#gem 'rake', :path=> '/mnt/storage1/users/s/sv/svs16/gem/gems/rake-10.0.3'
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem 'jquery-rails'
gem 'haml'
gem 'haml-rails'
gem 'twitter-bootstrap-rails'
group :production do
  gem 'rails_12factor'
end

gem 'sorcery'
gem 'execjs'
gem 'therubyracer', :platforms => :ruby
gem "paperclip", "~> 2.7"
gem 'kaminari'
gem 'i18n'
gem 'gnuplot'

gem 'russian', '~> 0.6.0'

gem 'carrierwave'
gem 'rubyzip'
gem 'protected_attributes'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
